### ISSUE TITLE
I think the provided code implements a simple DNS resolver, which can be used to look up DNS records for a given domain name. It's not a full-fledged DNS server but rather a DNS client capable of sending DNS queries to a DNS server and processing the responses.

### ISSUE THREAD

**Issue by JeninSutradhar** [EmilHernvall/dnsguide#25]

**Comment by EmilHernvall** [comment]
Quoting [wikipedia](https://en.wikipedia.org/wiki/Name_server#Types_of_Nameservers):

```
Types of Nameservers

Namservers are usually either authoritative or recursive, as described below. 
```

As you noted, this guide describes the implementation of a recursive nameserver rather than an authoritative. The reasoning is that the algorithm for recursive name resolution is quite interesting, whereas serving a single zone is conceptually straight forward. For an example of that, you can see my toy server here https://github.com/EmilHernvall/hermes which implements both an authoritative and a recursive mode.
